import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.image.BufferedImage;
import java.io.InputStream;

import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.Timer;


public class GUI extends JFrame  {
	
	private InputStream ais=null;
	private InputStream vis=null;
	private Timer timer = null;
	private PlaySound sound=null;
	private PlayVideo video=null;
	private int period=0;
	
	//GUI componnet parts
	private JLabel lbScreen;
	private JPanel pnPanel0;
	private JButton btStartButton;
	private JButton btBut2;
	boolean isStart=true;
	public GUI(InputStream ais, InputStream vis) {
		this.ais=ais;
		this.vis=vis;	
	
		sound=new PlaySound(ais);
		video=new PlayVideo(vis);
		period= 33;
		JPanel pannel=getMyLayout();
		getContentPane().add(pannel);
		pack();
		setVisible(true);
	}
	
	/**
	 * This Function is generated by java GUI tools
	 * @return Jpanel
	 */
	private JPanel getMyLayout() {
	
		pnPanel0 = new JPanel();
		pnPanel0.setBorder( BorderFactory.createTitledBorder( "Player" ) );
		GridBagLayout gbPanel0 = new GridBagLayout();
		GridBagConstraints gbcPanel0 = new GridBagConstraints();
		pnPanel0.setLayout( gbPanel0 );

		lbScreen = new JLabel(new ImageIcon(video.getNextFrame()));
		gbcPanel0.gridx = 0;
		gbcPanel0.gridy = 0;
		gbcPanel0.gridwidth = 28;
		gbcPanel0.gridheight = 18;
		gbcPanel0.fill = GridBagConstraints.BOTH;
		gbcPanel0.weightx = 1;
		gbcPanel0.weighty = 1;
		gbcPanel0.anchor = GridBagConstraints.NORTH;
		gbPanel0.setConstraints( lbScreen, gbcPanel0 );
		pnPanel0.add( lbScreen );

		btStartButton = new JButton( "Start/Pause"  );
		btStartButton.addActionListener(new StartPauseActionListner());
		gbcPanel0.gridx = 7;
		gbcPanel0.gridy = 18;
		gbcPanel0.gridwidth = 1;
		gbcPanel0.gridheight = 2;
		gbcPanel0.fill = GridBagConstraints.BOTH;
		gbcPanel0.weightx = 1;
		gbcPanel0.weighty = 0;
		gbcPanel0.anchor = GridBagConstraints.NORTH;
		gbPanel0.setConstraints( btStartButton, gbcPanel0 );
		pnPanel0.add( btStartButton );

		btBut2 = new JButton( "Stop"  );
		btBut2.addActionListener(new StopActionListner());
		gbcPanel0.gridx = 17;
		gbcPanel0.gridy = 18;
		gbcPanel0.gridwidth = 1;
		gbcPanel0.gridheight = 2;
		gbcPanel0.fill = GridBagConstraints.BOTH;
		gbcPanel0.weightx = 1;
		gbcPanel0.weighty = 0;
		gbcPanel0.anchor = GridBagConstraints.NORTH;
		gbPanel0.setConstraints( btBut2, gbcPanel0 );
		pnPanel0.add( btBut2 );
		return pnPanel0;
	}

	public void run() {
		
		// millicsecond
		timer=new Timer(0, new ActionListener() {
			long last=System.currentTimeMillis();
			int frame_num=0;
			@Override
			public void actionPerformed(ActionEvent e) {
				long tmp=System.currentTimeMillis();
				if ((tmp-last)>=period){
					update();
					last=tmp;
					frame_num++;
					if(frame_num==3){
						frame_num=0;
						period=34;
					}else{
						period=33;
					}
				}
			
				
			}
		});
		timer.start();
		sound.play();
	}
	public void update(){
		// updata vedio
		BufferedImage img=video.getNextFrame();
		lbScreen.setIcon(null);
		ImageIcon icon=new ImageIcon(img);
		icon.getImage().flush();
		lbScreen.setIcon(icon);
		repaint();
		// update audio
	}
	
	
	private class StartPauseActionListner implements ActionListener{
		
		
		@Override
		public void actionPerformed(ActionEvent e) {
			if(isStart==true){
				isStart=false;
				timer.stop(); // times stop as a result video will stop 
				sound.pause();
			}else{
				isStart=true;
				timer.start();// times start as a result video will start 
				sound.resume();
			}
		}
		
	}
	private class StopActionListner implements ActionListener{

		@Override
		public void actionPerformed(ActionEvent e) {
			
		}
		
	}

}
